# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: engmsg2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='engmsg2.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rengmsg2.proto\"\x86\x01\n\x0bReplyHeader\x12\x16\n\x0e\x65ngine_version\x18\x01 \x02(\t\x12\x1d\n\treplycode\x18\x02 \x02(\x0e\x32\n.ReplyCode\x12\x1b\n\x07\x65rrcode\x18\x03 \x01(\x0e\x32\n.ErrorCode\x12\x10\n\x08\x65rr_desc\x18\x04 \x01(\t\x12\x11\n\ttime_used\x18\x05 \x02(\r\"u\n\x0f\x44iabeticRequest\x12\x16\n\x0e\x63lient_version\x18\x01 \x02(\t\x12\x1e\n\x08\x64\x61tatype\x18\x02 \x02(\x0e\x32\x0c.ImgDataType\x12\x0b\n\x03img\x18\x03 \x02(\x0c\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\r\"c\n\rDiabeticReply\x12\x1c\n\x06header\x18\x01 \x02(\x0b\x32\x0c.ReplyHeader\x12\x14\n\x0cpreprocessed\x18\x02 \x02(\x0c\x12\x0c\n\x04prob\x18\x03 \x02(\x01\x12\x10\n\x08severity\x18\x04 \x02(\r\"v\n\x10XChestSegRequest\x12\x16\n\x0e\x63lient_version\x18\x01 \x02(\t\x12\x1e\n\x08\x64\x61tatype\x18\x02 \x02(\x0e\x32\x0c.ImgDataType\x12\x0b\n\x03img\x18\x03 \x02(\x0c\x12\r\n\x05width\x18\x04 \x01(\r\x12\x0e\n\x06height\x18\x05 \x01(\r\"D\n\x0eXChestSegReply\x12\x1c\n\x06header\x18\x01 \x02(\x0b\x32\x0c.ReplyHeader\x12\x14\n\x0clabelled_img\x18\x02 \x02(\x0c*4\n\x0bRequestCode\x12\x11\n\x0cREQ_Diabetic\x10\xc1>\x12\x12\n\rREQ_XChestSeg\x10\xc2>*\\\n\tReplyCode\x12\x06\n\x02OK\x10\x00\x12\x14\n\x07\x45RR_API\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x16\n\tERR_PROTO\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n\x0c\x45RR_INTERNAL\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01*g\n\tErrorCode\x12\x11\n\x0c\x45RR_IMG_DATA\x10\xe9\x07\x12\x13\n\x0e\x45RR_IMG_DATA_2\x10\xea\x07\x12\x16\n\x11\x45RR_IMG_TOO_SMALL\x10\xeb\x07\x12\x1a\n\x15\x45RR_NO_OBJ_DETECTED_1\x10\xec\x07*/\n\x0bImgDataType\x12\x08\n\x04ORIG\x10\x00\x12\r\n\tRGB_ARRAY\x10\x01\x12\x07\n\x03URI\x10\x02')
)

_REQUESTCODE = _descriptor.EnumDescriptor(
  name='RequestCode',
  full_name='RequestCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQ_Diabetic', index=0, number=8001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQ_XChestSeg', index=1, number=8002,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=564,
  serialized_end=616,
)
_sym_db.RegisterEnumDescriptor(_REQUESTCODE)

RequestCode = enum_type_wrapper.EnumTypeWrapper(_REQUESTCODE)
_REPLYCODE = _descriptor.EnumDescriptor(
  name='ReplyCode',
  full_name='ReplyCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_API', index=1, number=-1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_PROTO', index=2, number=-2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_INTERNAL', index=3, number=-3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=618,
  serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_REPLYCODE)

ReplyCode = enum_type_wrapper.EnumTypeWrapper(_REPLYCODE)
_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERR_IMG_DATA', index=0, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_IMG_DATA_2', index=1, number=1002,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_IMG_TOO_SMALL', index=2, number=1003,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERR_NO_OBJ_DETECTED_1', index=3, number=1004,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=712,
  serialized_end=815,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
_IMGDATATYPE = _descriptor.EnumDescriptor(
  name='ImgDataType',
  full_name='ImgDataType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ORIG', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RGB_ARRAY', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='URI', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=817,
  serialized_end=864,
)
_sym_db.RegisterEnumDescriptor(_IMGDATATYPE)

ImgDataType = enum_type_wrapper.EnumTypeWrapper(_IMGDATATYPE)
REQ_Diabetic = 8001
REQ_XChestSeg = 8002
OK = 0
ERR_API = -1
ERR_PROTO = -2
ERR_INTERNAL = -3
ERR_IMG_DATA = 1001
ERR_IMG_DATA_2 = 1002
ERR_IMG_TOO_SMALL = 1003
ERR_NO_OBJ_DETECTED_1 = 1004
ORIG = 0
RGB_ARRAY = 1
URI = 2



_REPLYHEADER = _descriptor.Descriptor(
  name='ReplyHeader',
  full_name='ReplyHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='engine_version', full_name='ReplyHeader.engine_version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replycode', full_name='ReplyHeader.replycode', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errcode', full_name='ReplyHeader.errcode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1001,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='err_desc', full_name='ReplyHeader.err_desc', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_used', full_name='ReplyHeader.time_used', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=152,
)


_DIABETICREQUEST = _descriptor.Descriptor(
  name='DiabeticRequest',
  full_name='DiabeticRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_version', full_name='DiabeticRequest.client_version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='DiabeticRequest.datatype', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='img', full_name='DiabeticRequest.img', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='DiabeticRequest.width', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='DiabeticRequest.height', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=271,
)


_DIABETICREPLY = _descriptor.Descriptor(
  name='DiabeticReply',
  full_name='DiabeticReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='DiabeticReply.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='preprocessed', full_name='DiabeticReply.preprocessed', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob', full_name='DiabeticReply.prob', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='severity', full_name='DiabeticReply.severity', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=372,
)


_XCHESTSEGREQUEST = _descriptor.Descriptor(
  name='XChestSegRequest',
  full_name='XChestSegRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_version', full_name='XChestSegRequest.client_version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='XChestSegRequest.datatype', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='img', full_name='XChestSegRequest.img', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='XChestSegRequest.width', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='XChestSegRequest.height', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=492,
)


_XCHESTSEGREPLY = _descriptor.Descriptor(
  name='XChestSegReply',
  full_name='XChestSegReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='XChestSegReply.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='labelled_img', full_name='XChestSegReply.labelled_img', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=494,
  serialized_end=562,
)

_REPLYHEADER.fields_by_name['replycode'].enum_type = _REPLYCODE
_REPLYHEADER.fields_by_name['errcode'].enum_type = _ERRORCODE
_DIABETICREQUEST.fields_by_name['datatype'].enum_type = _IMGDATATYPE
_DIABETICREPLY.fields_by_name['header'].message_type = _REPLYHEADER
_XCHESTSEGREQUEST.fields_by_name['datatype'].enum_type = _IMGDATATYPE
_XCHESTSEGREPLY.fields_by_name['header'].message_type = _REPLYHEADER
DESCRIPTOR.message_types_by_name['ReplyHeader'] = _REPLYHEADER
DESCRIPTOR.message_types_by_name['DiabeticRequest'] = _DIABETICREQUEST
DESCRIPTOR.message_types_by_name['DiabeticReply'] = _DIABETICREPLY
DESCRIPTOR.message_types_by_name['XChestSegRequest'] = _XCHESTSEGREQUEST
DESCRIPTOR.message_types_by_name['XChestSegReply'] = _XCHESTSEGREPLY
DESCRIPTOR.enum_types_by_name['RequestCode'] = _REQUESTCODE
DESCRIPTOR.enum_types_by_name['ReplyCode'] = _REPLYCODE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
DESCRIPTOR.enum_types_by_name['ImgDataType'] = _IMGDATATYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReplyHeader = _reflection.GeneratedProtocolMessageType('ReplyHeader', (_message.Message,), dict(
  DESCRIPTOR = _REPLYHEADER,
  __module__ = 'engmsg2_pb2'
  # @@protoc_insertion_point(class_scope:ReplyHeader)
  ))
_sym_db.RegisterMessage(ReplyHeader)

DiabeticRequest = _reflection.GeneratedProtocolMessageType('DiabeticRequest', (_message.Message,), dict(
  DESCRIPTOR = _DIABETICREQUEST,
  __module__ = 'engmsg2_pb2'
  # @@protoc_insertion_point(class_scope:DiabeticRequest)
  ))
_sym_db.RegisterMessage(DiabeticRequest)

DiabeticReply = _reflection.GeneratedProtocolMessageType('DiabeticReply', (_message.Message,), dict(
  DESCRIPTOR = _DIABETICREPLY,
  __module__ = 'engmsg2_pb2'
  # @@protoc_insertion_point(class_scope:DiabeticReply)
  ))
_sym_db.RegisterMessage(DiabeticReply)

XChestSegRequest = _reflection.GeneratedProtocolMessageType('XChestSegRequest', (_message.Message,), dict(
  DESCRIPTOR = _XCHESTSEGREQUEST,
  __module__ = 'engmsg2_pb2'
  # @@protoc_insertion_point(class_scope:XChestSegRequest)
  ))
_sym_db.RegisterMessage(XChestSegRequest)

XChestSegReply = _reflection.GeneratedProtocolMessageType('XChestSegReply', (_message.Message,), dict(
  DESCRIPTOR = _XCHESTSEGREPLY,
  __module__ = 'engmsg2_pb2'
  # @@protoc_insertion_point(class_scope:XChestSegReply)
  ))
_sym_db.RegisterMessage(XChestSegReply)


# @@protoc_insertion_point(module_scope)
