# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 07:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20170629_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
