# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20170629_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='Image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
