# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20170629_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Name'),
        ),
    ]
