# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='profile'),
        ),
    ]
