# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_merge_20170710_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='Image',
            field=models.ImageField(upload_to='img\\'),
        ),
    ]
